### ISSUE TITLE
Implement task state rationalization proposal

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4013]
Complete task state rationalization as described in [this proposal](https://cylc.github.io/cylc-admin/proposal-state-names.html)

- [x] (waiting, queued, runahead) -> waiting (finished by #4035)
- [x] ready -> preparing  #4014
- [x] retrying, submit-retrying: re-implement as xtrigger  #3423
- [x] held: re-implement as attribute  #3230

Note we decided not to do the proposed trivial renaming (succeeded -> run-succeeded, etc.).
