### ISSUE TITLE
cylc clean: improvements

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4673]
- [x] Replace current `--force` option with `--yes / -y` - more apt (#4675)
  - Should `--force` come back in a different form? E.g. #4450
- [x] Doing `cylc clean toplevel` and typing `y` at the interactive step for a workflow dir `toplevel` containing multiple runs, does not actually remove `~/cylc-run/toplevel` at the moment (moved to #4963)
- [x] Improve message for incompatible database - give instructions for how to manually delete db (#4876)
  - alternative to #4450

**Pull requests welcome!**
